sorting: sorting1558365.o quicksort.o mergesort.o insertionsort.o bubblesort.o selectionsort.o heapsort.o
	gcc -o sorting sorting1558365.o quicksort.o mergesort.o insertionsort.o bubblesort.o selectionsort.o heapsort.o

sorting1558365.o: sorting1558365.c sorting1558365.h
	gcc -c sorting1558365.c

quicksort.o: quicksort.c quicksort.h
	gcc -c quicksort.c

mergesort.o: mergesort.c mergesort.h
	gcc -c mergesort.c

insertionsort.o: insertionsort.c insertionsort.h
	gcc -c insertionsort.c

bubblesort.o: bubblesort.c bubblesort.h
	gcc -c bubblesort.c

selectionsort.o: selectionsort.c selectionsort.h
	gcc -c selectionsort.c

heapsort.o: heapsort.c heapsort.h
	gcc -c heapsort.c